# Generated by Django 4.2.2 on 2023-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.ImageField(null=True, upload_to='portafolio/icons'),
        ),
    ]
